// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A intelligent rerouting AI agent that suggests alternative routes
 * based on real-time traffic conditions and predicted congestion.
 *
 * - intelligentRerouting - A function that handles the rerouting process.
 * - IntelligentReroutingInput - The input type for the intelligentRerouting function.
 * - IntelligentReroutingOutput - The return type for the intelligentRerouting function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const IntelligentReroutingInputSchema = z.object({
  currentRoute: z.string().describe('The current route the user is taking.'),
  currentTrafficConditions: z
    .string()
    .describe('Real-time traffic conditions on the current route.'),
  predictedCongestion: z
    .string()
    .describe('Predicted congestion on the current route.'),
  destination: z.string().describe('The destination of the route.'),
  origin: z.string().describe('The origin of the route.'),
});
export type IntelligentReroutingInput = z.infer<typeof IntelligentReroutingInputSchema>;

const IntelligentReroutingOutputSchema = z.object({
  alternativeRoutes: z
    .array(z.string())
    .describe('Alternative routes based on traffic conditions and predicted congestion.'),
  reasoning: z.string().describe('The reasoning behind suggesting these alternative routes.'),
});
export type IntelligentReroutingOutput = z.infer<typeof IntelligentReroutingOutputSchema>;

export async function intelligentRerouting(input: IntelligentReroutingInput): Promise<IntelligentReroutingOutput> {
  return intelligentReroutingFlow(input);
}

const prompt = ai.definePrompt({
  name: 'intelligentReroutingPrompt',
  input: {schema: IntelligentReroutingInputSchema},
  output: {schema: IntelligentReroutingOutputSchema},
  prompt: `You are a route optimization expert. Given the current route, traffic conditions, predicted congestion, origin, and destination, suggest alternative routes that avoid delays and reach the destination faster.

Current Route: {{{currentRoute}}}
Current Traffic Conditions: {{{currentTrafficConditions}}}
Predicted Congestion: {{{predictedCongestion}}}
Destination: {{{destination}}}
Origin: {{{origin}}}

Consider all factors and provide a list of alternative routes along with a reasoning for each suggestion.

Alternative Routes:
`,
});

const intelligentReroutingFlow = ai.defineFlow(
  {
    name: 'intelligentReroutingFlow',
    inputSchema: IntelligentReroutingInputSchema,
    outputSchema: IntelligentReroutingOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
